Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967295 for virtual address 0xffffffff!
Python script tests/../scripts/macho.py's mapAddress function returned out-of-bounds offset 4294967040 for virtual address 0xffffff00!
Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file llvm-3.9.0/include/llvm/Support/Casting.h, line 237.
